[package]
name = "carillon-core"
description = "Shared async watch client for Carillon"
version = "0.0.0"
authors = ["soywod <pimalaya.org@posteo.net>"]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["email", "asynchronous"]
keywords = ["watch", "imap", "carddav", "idle", "notification"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/carillon-core/latest/carillon_core"
repository = "https://github.com/pimalaya/carillon-core"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["imap"]
imap = ["dep:anyhow", "dep:io-imap", "dep:log"]

[dependencies]
anyhow = { version = "1", optional = true }
io-imap = { version = "0.2", default-features = false, optional = true }
log = { version = "0.4", default-features = false, optional = true }
rand = "0.10"
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", default-features = false }
tokio = { version = "1", default-features = false, features = ["io-util", "sync", "time"] }
