[package]
name = "carillon-core"
description = "Shared I/O-free watch client for Carillon"
version = "0.0.0"
authors = ["soywod <pimalaya.org@posteo.net>"]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["email", "no-std"]
keywords = ["watch", "imap", "carddav", "idle", "notification"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/carillon-core/latest/carillon_core"
repository = "https://github.com/pimalaya/carillon-core"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["imap"]
imap = ["dep:io-imap"]
carddav = ["dep:io-webdav", "dep:io-http", "dep:url"]

[dependencies]
io-http = { version = "0.3", default-features = false, optional = true }
io-imap = { version = "0.2", default-features = false, optional = true }
io-webdav = { version = "0.1", default-features = false, optional = true }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", default-features = false }
url = { version = "2", optional = true }

[dev-dependencies]
secrecy = "0.10"
